### ISSUE TITLE
Wrong attributes on AssetAdministrationShell class?

### ISSUE THREAD

**Issue by Pabzt** [aas-core-works/aas-core3.0-csharp#17]
Hi,

according to the current version of the spec.: https://industrialdigitaltwin.org/wp-content/uploads/2023/05/V3.0_Specification_AAS_Part1_Metamodel.pdf (page: 59)

the AssetAdministrationShell class only has the following attributes:
- derivedFrom
- assetInformation
- submodel

and inherits from: Identifiable; HasDataSpecification.

While the core works AssetAdministrationShell class has the same attributes there are also other ones like:
- extensions
- category
- displayname
- description
...

Both state to be version 3.0. Am I missing something?

**Comment by mristin** [comment]
Hi @Pabzt,
We do not implement inheritance to avoid problems with diamond inheritances and decorators. The smaller set of properties are specified in the respective interfaces.
