### ISSUE TITLE
JSON Deserialization: Property with semanticId=null accepted

### ISSUE THREAD

**Issue by otto-ifak** [aas-core-works/aas-core3.0-csharp#41]
The following JSON is accepted, although `semanticId` is `null`:

```json
{
    "submodels": [
        {
            "modelType": "Submodel",
            "id": "x",
            "submodelElements": [
                {
                    "idShort": "x",
                    "modelType": "Property",
                    "valueType": "xs:string",
                    "semanticId": null
                }
            ]
        }
    ]
}
```

**Comment by mristin** [comment]
@otto-ifak can you please clarify a bit? Semantic ID is optional here, isn't it?

As far as ai know, you can not distinguish in C# whether a JSON property is set to null or absent.

**Comment by otto-ifak** [comment]
You can query the parent object using `ContainsKey`:
```c#
      using System.Text.Json.Nodes;
      string jsonString = """
          {
              "semanticId": null
          }
          """;
      JsonNode node = JsonNode.Parse(jsonString)!;
      var hasFoo = node.AsObject().ContainsKey("foo");
      var hasSemanticId = node.AsObject().ContainsKey("semanticId");
      Console.WriteLine($"hasFoo={hasFoo}, hasSemanticId={hasSemanticId}");
     // hasFoo=False, hasSemanticId=True
```

**Comment by mristin** [comment]
@otto-ifak I think the reason I didn't implement it that way is that you have to do two lookups -- but let me double-check.

**Comment by otto-ifak** [comment]
Unfortunately, I am not a c# dev. But I am quite sure that there is a way to do his with one lookup and maybe exception handling...
If it helps, here is the doc for the JsonObject class:
https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonobject?view=net-8.0
